### ISSUE TITLE
angular 2

### ISSUE THREAD

**Issue by kindlychung** [joescii/lift-ng#14]
Any plans for supporting angular 2?

**Comment by joescii** [comment]
Not from me.  I will gladly help anyone who would like to explore how lift-ng can be a valuable library for Angular 2 apps.  The primary reason I chose Angular to go along with Lift is it supports view-first development very naturally.  I feel that Angular 2's approach to move the DOM predominantly into the javascript source moves the library away from view-first development.  Because of that movement away from what I think is a really nice synergy between Lift and Angular, I'm not very compelled to put any effort towards it.
