### ISSUE TITLE
deprecated jsoncall

### ISSUE THREAD

**Issue by colinbes** [joescii/lift-ng#16]
I see in source comments that jsoncall is deprecated but deprecated line is commented out.

Could you please confirm whether this function is deprecated or not?

Thanks!

**Comment by joescii** [comment]
I can't remember why I commented out the `deprecation`, but yes it is best you stop using `jsonCall`. Because it's overloaded, I'm unable to catch problems like your model not implementing `NgModel`. You should prefer the methods `defAny`, `defStringToAny`, and `defModelToAny`.

My eventual plan was to write a macro that would make the whole process smoother but I'm not sure when I'll get around to that. I left the team where I was using this module, so I'm not very motivated to keep polishing it. I'll certainly be maintaining it for any bugs, but fortunately those are rare.

I'll leave this open as a reminder to finish this up.

**Comment by colinbes** [comment]
Thanks Joe, appreciate the feedback and all the best with current endeavors although you will be sorely missed on this project, you've done an excellent job!

**Comment by joescii** [comment]
Code complete https://github.com/joescii/lift-ng/tree/remove-ng-model2
