### ISSUE TITLE
Suggestions on how to provide service to handle redirect

### ISSUE THREAD

**Issue by colinbes** [joescii/lift-ng#44]
Toying with different ideas, but am looking for way to provide a 'click action' client side and have it call server side function for server to implement and handle redirect.

Any ideas?

**Comment by joescii** [comment]
So you want to use something like `S.redirectTo()`?

**Comment by colinbes** [comment]
Basically yes. I want a click event of client side to call a server side function where server decides on where to redirect to and then redirects.

I eventually ended up using binding csssel

```
"#asdf2 [onclick]" #> SHtml.onEvent((str)=>{
          S.redirectTo("posts", () => RemotePostsVar.set(Full(editUser)))
          JsCmds.Noop
})
```

**Comment by colinbes** [comment]
Opening this again as I am obviously being very dense.

I am looking at providing a service gotoPage where once called, the server will make decision on where to redirect to.

.defAny("gotoPage", ()=>{some logic, then redirectTo(...)) 

I know I can't use S.redirectTo and JsCmds RedirectTo is an ajax thingy (technical term) so that won't work, I could simply pass back string and have client use location to redirect, but I'd prefer to have redirect command come from server side.

Hope this makes some sense...
Am I over thinking things?

**Comment by colinbes** [comment]
Forgot to open...

**Comment by joescii** [comment]
I'm not surprised you're looking for suggestions in this particular case. I wouldn't think Angular would ever expect a redirect from an `$http` call since that world is more about SPA. Hence the Angular way would probably be to return the string to redirect to, as you pointed out. If you want this happening from the server side, then I think your original pure-Lift approach is the way to go. I think the idea of an Angular server call resulting in a redirect is not really an expected pattern to follow.

**Comment by joescii** [comment]
Yeah, it's certainly the more secure approach :)
