### ISSUE TITLE
Clarification on use of execution content in release 0.12.x

### ISSUE THREAD

**Issue by colinbes** [joescii/lift-ng#46]
In ReadMe under Configuration section it states _"If you plan to use futures of type scala.concurrent.Future[T] ... By default, we will use scala.concurrent.ExecutionContext.global. To specify a different ExecutionContext, in your Boot.boot invoke the apply method of net.liftmodules.ng.AngularExecutionContext...."_

And under Change log 0.12.0 mention is made that _"All implicit scala.concurrent.ExecutionContext parameters have been replaced by our own ExecutionContextProvider trait."_ and to use net.liftmodules.ng.AngularExecutionContext._ if not using lift-cluster.

Is first paragraph correct in that scala.concurrent.ExecutionContext is used by default and does this imply that for 0.12.x we must use net.liftmodules.ng.AngularExecutionContext(context) to set ec to net.liftmodules.ng.AngularExecutionContext provided ec instead boot.scala during setup?

**Comment by colinbes** [comment]
Digging deeper it appears that net.liftmodules.ng.AngularExecutionContext is using scala.concurrent.ExecutionContext

**Comment by joescii** [comment]
Do you have the understanding you need now? In `Boot` you can specify the execution context provider you want to use, assuming the default `scala.concurrent.ExecutionContext.global` isn't what you want. Then anywhere you create a lift-ng service with method passing a `Future`, import `net.liftmodules.ng.AngularExecutionContext._` rather than your usual `ExecutionContext`.

**Comment by colinbes** [comment]
Thanks Joe, seeing the code cleared it up for me, what led to initial post was what I read as a contradiction in two sections of document.
Thanks for rapid response.
